steps:
- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/serious-habitat-281404/dateapi', '.']
- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/serious-habitat-281404/dateapi']
